### PR TITLE
Fix #28

### LINKED ISSUE #28: [Bug]: wrong parameter name in IncomingWebhookReceived constructor
### Plugin version

1.0.x-dev

### Sylius version

v1.10.2

### What happened?

When using this plugin and set async transport for `IncomingWebhookReceived` message you will get such an error when try to consume messages:

`Cannot create an instance of "Setono\SyliusWebhookPlugin\Message\Event\IncomingWebhookReceived" from serialized data because its constructor requires parameter "incomingWebhook" to be present.  `

And it's logical, because the serialized payload is `{"incoming_webhook_id":"13aaf0f4-cf51-4fcc-9d73-a4cc8b949443"}`
and in `IncomingWebhookReceived` constructor it's parameter name is `$incomingWebhook`

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by next-sentence**

### CODE REVIEW

**Comment by loevgaard** [comment]
What does this PR fix? I am not sure what the difference is? Can you elaborate?

**Comment by next-sentence** [comment]
When symfony serializer encode the `IncomingWebhookReceived::class` it's result something like this `{"incoming_webhook_id":"13aaf0f4-cf51-4fcc-9d73-a4cc8b949443"}`, all is fine until the same serializer try to deserialize this payload into `IncomingWebhookReceived` with `public function __construct($incomingWebhook)`

`"incoming_webhook_id" !== $incomingWebhook`

it should be the same: `$incomingWebhookId`

**Comment by next-sentence** [comment]
Or you have to write some serializer config:

```
Setono\SyliusWebhookPlugin\Message\Event\IncomingWebhookReceived:
    attributes:
        incomingWebhookId:
            serialized_name: incoming_webhook
```

**Comment by loevgaard** [comment]
What does the property name have to do with the name of the constructor argument? Also the default serializer in Symfony Messenger is the PhpSerializer which doesn't serialize the way you show here. Did you do something custom?

**Comment by next-sentence** [comment]
> What does the property name have to do with the name of the constructor argument?

lol, how symfony serializer should know to set the corect value, if you don't have any setters and only constructor args??

> Did you do something custom?

yes, I'm not using default php serializer:
```

framework:
    messenger:
        serializer:
            default_serializer: messenger.transport.symfony_serializer
            symfony_serializer:
                format: json
```

**Comment by next-sentence** [comment]
maybe you didn't see #28

**Comment by loevgaard** [comment]
> lol, how symfony serializer should know to set the corect value, if you don't have any setters and only constructor args??

I am trying to help you solve your problem. No need to laugh...

Could you try this instead:

1. Make the property public
2. Remove the getter
3. Test it in your application

**Comment by next-sentence** [comment]
> I am trying to help you solve your problem.

I already fixed my problem with serializer config, just wanted to help other people that would fall into same issue.



> No need to laugh...

Sorry ((


> Could you try this instead:
> 
> 1. Make the property public
> 2. Remove the getter
> 3. Test it in your application

This won't help, the error will be the same because of constructor argument name: 
`Cannot create an instance of "Setono\SyliusWebhookPlugin\Message\Event\IncomingWebhookReceived" from serialized data because its constructor requires parameter "incomingWebhook" to be present.`

**Comment by next-sentence** [comment]
I already fixed the issue in this pull request and don't understand why is this argue, what is wrong with my solution..?

**Comment by loevgaard** [comment]
You're lowering the DX with this PR and you're creating a BC break (although I know the plugin isn't tagged).

What would the serializer do if the constructor was private and we had a named constructor like `fromIncomingWebhook()`? Would it just fail then?

**Comment by vvasiloi** [comment]
@loevgaard from having an untyped constructor argument that can be interpreted in at least 2 ways and can even accept invalid values, like an integer for example, to having it typed, doing 1 thing and not accepting any invalid values is an improvement of DX and code quality.
The class IncomingWebhookReceived is final and is only keeping the webhook id and there's nothing someone else can change about it. It's not much o a public API.
Any customization will require a new message class and a new message handler class.

**Comment by loevgaard** [comment]
Great to have you join, @vvasiloi :D

The type safety is secured by the assertion: https://github.com/Setono/SyliusWebhookPlugin/blob/master/src/Message/Event/IncomingWebhookReceived.php#L23, so it cannot receive invalid values.

I admit that DX is a subjective matter. I have no problem with that :-)

It is a BC break. If a user instantiated the class with an object it would throw an exception after this PR.

But just to elaborate. I might have come across as being arrogant which was not my intent. I frankly didn't know that the Symfony Serializer couldn't handle this and from the changes I saw I just didn't think it added any value and _in my opinion_ it decreased the DX. If you read my comments with this in mind I hope you will see that I am actually trying to figure out what the SF serializer can accept and if we could make a PR that would still allow the end user to instantiate the `IncomingWebhookReceived` with either an instance or an id.

This PR could have been as simple as (I suppose):

```diff
- public function __construct($incomingWebhook)
+ public function __construct($incomingWebhookId)
```

and then for DX purposes:

```diff
/**
- * @param mixed|string|IncomingWebhookInterface $incomingWebhookId
+ * @param string|IncomingWebhookInterface $incomingWebhookId
  */
```

which would then have your static analysis catch any errors you might do as the end user.

Wdyt?

**Comment by vvasiloi** [comment]
The assertion doesn't help to prevent an issue with static analysis, it only reveals it on runtime when you execute the code.
But indeed, removing the option to pass an instance of IncomingWebhookInterface is not necessary to solve the issue.
The only thing required is to either rename the parameter or configure the serialized_name.
Your proposal looks good.

**Comment by loevgaard** [comment]
Done: https://github.com/Setono/SyliusWebhookPlugin/commit/baba1f64d5f7e98f1b6151441b181e435ea684f6. Are you using this plugin in a production environment? If so I can make a release

**Comment by vvasiloi** [comment]
Great! Thank you!
We're using it in a production environment.

**Comment by loevgaard** [comment]
https://github.com/Setono/SyliusWebhookPlugin/releases/tag/v0.1.0, there you go :)

**Pull request closed without merging**
